Monroe Township New Jersey'deki ev fiyatlarını tahmin edeceğiz. Ev fiyatları sadece m^2 değil birden fazla faktöre bağlıdır. Bu uygulamada yatak odası sayısı ve bina yaşını ekleyerek sorunumuzu daha karmaşık bir hale getiriyoruz.

Bir model oluşturduktan sonra;
* 3000 m2 alan, 3 yatakodası ve 40 yıllık bir bina
* 2500 m2 alan, 4 yatak odası ve 5 yıllık bina

bu iki binanın fiyat tahminini yapmaya çalışacağız.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
import os
os.chdir(r"C:\Users\sahik\Documents\MAKINE_OGRENMESI\DATA")

In [3]:
data = pd.read_csv("home_prices.csv")
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
data.fillna(data.bedrooms.median(), inplace=True)

In [10]:
data

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [17]:
X = data.drop(["price"], axis=1)
y = data.price

In [18]:
reg = LinearRegression()
reg.fit(X,y)

LinearRegression()

In [21]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [22]:
reg.intercept_

221323.00186540408

In [20]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [23]:
# y = m1.x1 + m2.x2 + m3.x3 + b
112.06244194 * 3000 + 23388.88007794 * 3 + (-3231.71790863) * 40 + 221323.00186540408

498408.2515740241

In [24]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

### ÖDEV:

Deneyime dayalı olarak bir form için işe alım verilerini içeren bir .csv dosyamız var. Yazılı test puanına ve kişisel görüşme puanına bakılarak aday maaşı elde edilmiştir. 

Bu veri setini kullanarak;
* 2 yıllık deneyim, yazılı test puanı 9, kişisel görüşme puanı 6
* 12 yıllık deneyim, yazılı test puanı 10, kişisel görüşme puanı 10

olan iki kişinin tahmini maaş değerlerini bulalım.

In [142]:
df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

Başlangıçta "experience - deneyim" kolonunda 2 NaN değer gözlemlenmektedir. Bu değerler kişinin hiçbir deneyimi olmadığını ifade etmektedir. Bu nedenle bunları sıfır olarak varsayabiliriz. Linear Regression genellikle sayılar üzerinde çalışır bu nedenle bu verileri sayılara çevirmeliyiz. Bunun için python da bulunan **"word2number"** modülünü kullanabiliriz.

> **word2number:** Bu, sayı kelimelerini (örn. two) sayısal rakamlara (2) dönüştürmek için bir Python modülüdür. (**!!!** Sayı kelimeleri ingilizce olmalı)
> * **from word2number import w2n** ile kütüphaneyi dahil ediyoruz.
> * Bir sayı-kelimeyi sayısal rakamlara dönüştürmek için **word_to_num** yöntemini kullanabilirsiniz.

In [47]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [74]:
from word2number import w2n

* Öncelikle "experience" kolonundaki NaN değerlerini "zero - 0" yapalım...

In [143]:
df["experience"].fillna("zero", inplace=True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

* Şimdi de sayı kelimelerini sayısal rakamlara çevirelim.

In [144]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

> **apply()** fonksiyonu içerisinde lambda kullanarak var olan değişkenin içerisinde değişiklik yapabilir ya da DataFrame objesi içerisinde yer alan değişkenlerden yeni değişkenler türetilebilir.

* Şimdi de "test_score" sütunundaki NaN değerlere ortalama değerleri atıyalım.

In [145]:
df["test_score(out of 10)"].mean()

7.857142857142857

In [146]:
import math
median_test_score = math.floor(df["test_score(out of 10)"].mean())
median_test_score

7

In [147]:
df["test_score(out of 10)"].fillna(median_test_score, inplace=True)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

* Verisetini düzenleme işlemi bitti. Şimdi modelimizi kurup tahmin değerlerimizi gözlemleyelim.

In [148]:
X_data = df.drop(["salary($)"], axis=1)
y_data = df["salary($)"]

In [149]:
rg = LinearRegression()
rg.fit(X_data, y_data)

LinearRegression()

In [150]:
rg.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [151]:
rg.intercept_

14992.65144669314

In [152]:
rg.predict([[2,9,6]])

array([53713.86677124])

In [153]:
rg.predict([[12,10,10]])

array([93747.79628651])